Added auto spark connection

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -77,7 +77,6 @@ services:
     environment:
       SERVICE_NAME: metastore
       DB_DRIVER: postgres
-      SKIP_SCHEMA_INIT: "true"
       SERVICE_OPTS: >-
         -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
         -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore
@@ -105,6 +104,8 @@ services:
       export HADOOP_CLIENT_OPTS=\"-Xmx1G -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore -Djavax.jdo.option.ConnectionUserName=hive -Djavax.jdo.option.ConnectionPassword=hive123\";
       echo 'Waiting 5 seconds for PostgreSQL...';
       sleep 5;
+      echo 'Initializing Hive Metastore schema...';
+      /opt/hive/bin/schematool -dbType postgres -initSchema --verbose || echo 'Schema already exists or initialization failed';
       echo 'Starting Hive Metastore...';
       /opt/hive/bin/hive --service metastore
       "
